name: Run tests for backwards compatibility


on: [push, pull_request_target]

jobs:
  build-and-run-servers:
    name: Run tests for backwards compatibility
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.3'
    - run: ls -la
    - run: chmod +x ./tests/test_backward_compatibility.sh
    - run: ./tests/test_backward_compatibility.sh

